# docker-compose.yml

version: '3.9'

services:
  app:
    build:
      context: .
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - src/.env
    command: ["sh", "app.sh"]

  db:
    image: postgres:15
    container_name: db_pg
    command: -p 5432
    expose:
      - 5432

    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

    env_file:
      - src/.env
    ports:
      - 5433:5432

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  pytest:
    build:
      context: ./
      dockerfile: Dockerfile_pytest
    container_name: pytest
    volumes:
      - ./src/tests/test:/src/tests/
    tty: true

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
    driver: local

